baseURL = 'https://m1n-4d316e.github.io/'
languageCode = 'es-es'
title = 'M1n-F1losof1a'
theme = "yinyang"
DefaultContentLanguage = "es"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "David"
  homepage = "https://github.com/M1n-4d316e"
  
[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2
  [languages.es]
    contentDir = "content/es"
    languageName = "Spanish"
    weight = 1

[params]
mainSections = ["posts"]
headTitle = "M1n-F1losof1a"
[[params.socials]]
name = "Github"
link = "https://github.com/M1n-4d316e"